services:
  automation-tests:
    build: .
    shm_size: "2gb"
    volumes:
      - .:/app
      - /app/node_modules
      - ./reports:/app/reports
      - ./errorShots:/app/errorShots
      - ./reports:/app/reports
