import fs from 'fs';
import path from 'path';

const reportDir = './reports/json-results';
const perfFilePath = './reports/perf-score.txt';

let totalTests = 0;
let passed = 0;
let failed = 0;
let realPerfScore = "N/A";

// 1. PROCESAR RESULTADOS DE TESTS (JSON)
if (fs.existsSync(reportDir)) {
    const files = fs.readdirSync(reportDir).filter(file => file.endsWith('.json'));
    
    files.forEach(file => {
        try {
            const content = JSON.parse(fs.readFileSync(path.join(reportDir, file), 'utf8'));
            totalTests += content.metrics.tests || 0;
            passed += content.metrics.passed || 0;
            failed += content.metrics.failed || 0;
        } catch (error) {
            console.error(`Error procesando el archivo ${file}:`, error);
        }
    });
}

if (fs.existsSync(perfFilePath)) {
    const score = fs.readFileSync(perfFilePath, 'utf8').trim();
    realPerfScore = `${score}/100`;
}

const passRate = totalTests > 0 ? ((passed / totalTests) * 100).toFixed(2) : 0;

const summary = `
## 📊 Stensul Quality Intelligence Report
> *Data processed from real-time execution logs (Databricks-style pipeline)*

| Metric | Real-Time Value |
| :--- | :--- |
| **Total Tests Executed** | ${totalTests} |
| **Pass Rate** | ${passRate}% ${passRate == 100 ? '✅' : '⚠️'} |
| **Lighthouse Performance** | ${realPerfScore} 🚀 |
| **Tests Passed** | ${passed} |
| **Tests Failed** | ${failed} |
| **Environment** | Production / Heroku |

### 🔍 Analysis Insight:
${failed > 0 
    ? "❌ **Critical Alert:** Regressions detected. The current build does not meet the stability threshold for Stensul's release standards." 
    : "💎 **Stability Confirmed:** All functional checkpoints passed. Performance audit shows no significant rendering regressions."}

---
*Generated by the QA Ecosystem - ${new Date().toLocaleString()}*
`;

if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);
    console.log("✅ Dashboard inyectado en el resumen de GitHub Actions.");
} else {
    console.log("\n--- [LOCAL REPORT PREVIEW] ---\n", summary);
}